'use client';

import React, { useState } from 'react';
import { BuilderSidebar } from '@/components/builder/sidebar';
import { BuilderCanvas } from '@/components/builder/canvas';
import { Button } from '@/components/ui/button';
import { 
  Save, Eye, Globe, ArrowLeft, Layout, Cpu, MessageSquare, 
  Sparkles, Monitor, Tablet, Smartphone, Download, Code,
  Undo2, Redo2, Play, Send, Bot, User, Trash2, Copy, Check
} from 'lucide-react';
import Link from 'next/link';
import { useBuilderStore } from '@/lib/builder-store';
import { generateFullHTML } from '@/lib/builder-renderer';
import { useToast } from '@/hooks/use-toast';
import { testAgent } from '@/ai/flows/test-agent-flow';
import { ScrollArea } from '@/components/ui/scroll-area';

export default function BuilderPage() {
  const { mode, setMode, blocks, reset, viewport, setViewport, botToken, undo, redo, past, future } = useBuilderStore();
  const { toast } = useToast();
  const [isTestChatOpen, setIsTestChatOpen] = useState(false);
  const [testMessages, setTestMessages] = useState<{role: 'user' | 'model', content: string}[]>([]);
  const [testInput, setTestInput] = useState('');
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [isCopied, setIsCopied] = useState(false);

  const generateBotCode = (blocks: any[], token: string) => {
    const commands = blocks
      .filter(b => b.type === 'command')
      .map(b => `bot.command('${b.content.commandName.replace('/', '')}', (ctx) => ctx.reply(\`${b.content.description || 'Command executed'}\`));`)
      .join('\n');

    const replies = blocks
      .filter(b => b.type === 'reply')
      .map(b => `bot.on('message', (ctx) => ctx.reply(\`${b.content.description}\`));`)
      .join('\n');

    return `/**
 * Generated by Web3CyberServices Builder
 * Telegram Bot (Telegraf.js)
 */

const { Telegraf } = require('telegraf');

const BOT_TOKEN = '${token || 'YOUR_TELEGRAM_BOT_TOKEN'}';
const bot = new Telegraf(BOT_TOKEN);

bot.use((ctx, next) => {
  console.log(\`Update: \${ctx.updateType}\`);
  return next();
});

${commands || '// No commands'}

${replies || '// No replies'}

bot.launch()
  .then(() => console.log('Nexus Bot online'))
  .catch((err) => console.error('Launch failed:', err));

process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
`;
  };

  const generateAgentConfig = (blocks: any[]) => {
    const systemPrompt = blocks.find(b => b.type === 'system-prompt')?.content.systemPrompt || '';
    const tools = blocks.find(b => b.type === 'tools')?.content.tools || [];
    const knowledge = blocks.find(b => b.type === 'knowledge')?.content.knowledgeSources || [];

    return JSON.stringify({
      version: "1.0.0",
      agent: {
        instructions: systemPrompt,
        capabilities: tools,
        knowledge_base: knowledge,
      },
      metadata: {
        generated_at: new Date().toISOString()
      }
    }, null, 2);
  };

  const handleExport = () => {
    try {
      if (mode === 'landing') {
        const html = generateFullHTML(blocks);
        downloadFile(html, 'project.html', 'text/html');
      } else if (mode === 'ai-agent') {
        const config = generateAgentConfig(blocks);
        downloadFile(config, 'agent-config.json', 'application/json');
      } else if (mode === 'bot') {
        const code = generateBotCode(blocks, botToken);
        downloadFile(code, 'bot.js', 'application/javascript');
      }
      toast({ title: "Export Successful" });
    } catch (error) {
      toast({ title: "Export Failed", variant: "destructive" });
    }
  };

  const handleCopyCode = async () => {
    let content = "";
    if (mode === 'bot') content = generateBotCode(blocks, botToken);
    else if (mode === 'ai-agent') content = generateAgentConfig(blocks);
    else content = generateFullHTML(blocks);

    await navigator.clipboard.writeText(content);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
    toast({ title: "Copied to clipboard" });
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleTestChat = async () => {
    if (!testInput.trim() || isAiLoading) return;
    
    const userMsg = testInput;
    setTestInput('');
    setTestMessages(prev => [...prev, { role: 'user', content: userMsg }]);
    setIsAiLoading(true);

    try {
      const systemBlock = blocks.find(b => b.type === 'system-prompt');
      const systemPrompt = systemBlock?.content.systemPrompt || "You are a helpful assistant.";
      
      const response = await testAgent({
        systemPrompt,
        userMessage: userMsg,
        history: testMessages
      });

      setTestMessages(prev => [...prev, { role: 'model', content: response }]);
    } catch (e) {
      toast({ title: "Test Failed", variant: "destructive" });
    } finally {
      setIsAiLoading(false);
    }
  };

  if (!mode) {
    return (
      <div className="h-screen w-full bg-background flex flex-col items-center justify-center p-6 relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary/10 blur-[150px] rounded-full -z-10" />
        <div className="text-center mb-12 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary/10 text-primary rounded-full text-[10px] font-bold uppercase tracking-widest">
            <Sparkles className="w-3 h-3" /> Workspace Selection
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight text-gradient">Build the future</h1>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl w-full">
          <ModeCard icon={Layout} title="Landing Page" desc="High-conversion sites." onClick={() => setMode('landing')} color="text-primary" bgColor="bg-primary/10" />
          <ModeCard icon={Cpu} title="AI Agent" desc="Neural instructions & RAG." onClick={() => setMode('ai-agent')} color="text-emerald-400" bgColor="bg-emerald-400/10" />
          <ModeCard icon={MessageSquare} title="Telegram Bot" desc="Telegraf.js logic." onClick={() => setMode('bot')} color="text-blue-400" bgColor="bg-blue-400/10" />
        </div>
        <Link href="/" className="mt-12">
          <Button variant="ghost" className="gap-2 text-muted-foreground hover:text-primary transition-colors">
            <ArrowLeft className="w-4 h-4" /> Exit
          </Button>
        </Link>
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col bg-background text-foreground overflow-hidden">
      <header className="h-12 border-b flex items-center justify-between px-4 bg-card shrink-0 z-50">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={reset}><ArrowLeft className="w-4 h-4" /></Button>
          <div className="flex items-center gap-2 pr-3 border-r h-5">
            <h1 className="font-bold text-[10px] uppercase tracking-wider">{mode.replace('-', ' ')}</h1>
          </div>
          <div className="flex items-center gap-1">
            <Button variant="ghost" size="icon" className="h-7 w-7" disabled={past.length === 0} onClick={undo}><Undo2 className="w-3.5 h-3.5" /></Button>
            <Button variant="ghost" size="icon" className="h-7 w-7" disabled={future.length === 0} onClick={redo}><Redo2 className="w-3.5 h-3.5" /></Button>
          </div>
        </div>
        
        <div className="flex items-center bg-secondary/30 rounded-full p-0.5 border h-8">
          <Button variant={viewport === 'desktop' ? 'secondary' : 'ghost'} size="icon" className="rounded-full h-6 w-6" onClick={() => setViewport('desktop')}><Monitor className="w-3 h-3" /></Button>
          <Button variant={viewport === 'tablet' ? 'secondary' : 'ghost'} size="icon" className="rounded-full h-6 w-6" onClick={() => setViewport('tablet')}><Tablet className="w-3 h-3" /></Button>
          <Button variant={viewport === 'mobile' ? 'secondary' : 'ghost'} size="icon" className="rounded-full h-6 w-6" onClick={() => setViewport('mobile')}><Smartphone className="w-3 h-3" /></Button>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="h-8 text-[9px] font-bold uppercase tracking-widest px-3" onClick={handleCopyCode}>
            {isCopied ? <Check className="w-3 h-3 mr-1" /> : <Copy className="w-3 h-3 mr-1" />}
            Copy
          </Button>
          {mode === 'ai-agent' && (
            <Button variant="outline" size="sm" onClick={() => setIsTestChatOpen(!isTestChatOpen)} className={`h-8 text-[9px] font-bold uppercase tracking-widest px-3 ${isTestChatOpen ? "bg-primary/10 text-primary border-primary" : ""}`}>
              <Play className="w-3 h-3 mr-1" /> Test
            </Button>
          )}
          <Button variant="secondary" size="sm" className="h-8 text-[9px] font-bold uppercase tracking-widest px-3" onClick={handleExport}>
            <Download className="w-3 h-3 mr-1" /> Export
          </Button>
          <Button size="sm" className="h-8 text-[9px] font-bold uppercase tracking-widest px-3"><Globe className="w-3 h-3 mr-1" /> Deploy</Button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden relative">
        <BuilderSidebar />
        <BuilderCanvas />
        
        {isTestChatOpen && mode === 'ai-agent' && (
          <div className="w-80 border-l bg-card flex flex-col animate-in slide-in-from-right duration-300 shadow-2xl z-40">
            <div className="p-3 border-b flex items-center justify-between">
              <h3 className="text-[9px] font-black uppercase tracking-[0.2em] flex items-center gap-2"><Bot className="w-3 h-3 text-primary" /> Test Agent</h3>
              <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setTestMessages([])}><Trash2 className="w-3 h-3" /></Button>
            </div>
            <ScrollArea className="flex-1 p-4">
              <div className="space-y-4">
                {testMessages.length === 0 && (
                  <div className="py-20 text-center opacity-20 italic text-[9px] uppercase tracking-widest">Waiting for input...</div>
                )}
                {testMessages.map((m, i) => (
                  <div key={i} className={`flex flex-col ${m.role === 'user' ? 'items-end' : 'items-start'}`}>
                    <div className={`max-w-[90%] p-3 rounded-2xl text-[10px] leading-relaxed ${m.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-secondary border border-white/5'}`}>
                      {m.content}
                    </div>
                  </div>
                ))}
                {isAiLoading && (
                  <div className="flex items-start gap-2 animate-pulse">
                    <div className="p-3 bg-secondary rounded-2xl text-[9px] uppercase tracking-widest font-bold opacity-40">Processing...</div>
                  </div>
                )}
              </div>
            </ScrollArea>
            <div className="p-3 border-t bg-background/50">
              <div className="flex gap-2">
                <input 
                  value={testInput} 
                  onChange={(e) => setTestInput(e.target.value)} 
                  onKeyDown={(e) => e.key === 'Enter' && handleTestChat()}
                  placeholder="Ask agent..." 
                  className="flex-1 bg-card border rounded-xl px-3 py-2 text-[10px] outline-none"
                />
                <Button size="icon" className="h-8 w-8" onClick={handleTestChat} disabled={isAiLoading}><Send className="w-3 h-3" /></Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ModeCard({ icon: Icon, title, desc, onClick, color, bgColor }: any) {
  return (
    <button onClick={onClick} className="group p-6 bg-card border rounded-[2rem] text-left hover:border-primary/50 transition-all flex flex-col items-start gap-3 shadow-sm relative overflow-hidden">
      <div className={`p-3 ${bgColor} rounded-xl group-hover:scale-110 transition-transform`}><Icon className={`w-6 h-6 ${color}`} /></div>
      <div>
        <h3 className="text-lg font-black tracking-tight">{title}</h3>
        <p className="text-[10px] text-muted-foreground mt-1 opacity-60">{desc}</p>
      </div>
    </button>
  );
}
